### PR TITLE
Retry Cucumber Scenarios

### PR DESCRIPTION
**Pull request by jpaolini**
## Proposed changes
Current retry option doesn't work for Cucumber unless you have the `scenarioLevelReporter` set to `true`.  However, doing that will not show steps in Report Portal.  This change sets the retry at the scenario level.  It does require `scenarioLevelReporter` being set to `false` so the steps are still reported.

### CODE REVIEW

**Comment by BorisOsipov** [comment]
Hi @jpaolini. What kind of retry mechanism do you use for cucumber? is it wdio or cucumber build in feature?

**Comment by BorisOsipov** [comment]
@jpaolini and many thanks for backporting fixes from you fork. Appreciate it.

**Comment by jpaolini** [comment]
This is for the cucumber retry, wdio passes the retry parameter from the wdio config cucumber.  Followed the docs from [here](https://webdriver.io/docs/retry.html), the Rerun Full Suites in Cucumber portion.  

```

For cucumber >=6 you can provide the retry configuration option along with a retryTagFilter optional parameter to have all or some of your failing scenarios get additional retries until succeeded. For this feature to work you need to set the scenarioLevelReporter to true.
```

For this library though, we need to leave `scenarioLevelReporter` set to `false`.  It’s already setup to report scenarios/steps correctly to Report Portal.  If it’s set to `true`, then in Report Portal, the steps won’t show.  Looks like it could be a pretty large refactor to have it work that way.

**Comment by BorisOsipov** [comment]
merged as https://github.com/BorisOsipov/wdio-reportportal-reporter/commit/4ee73947c0c3f28095184397334294e973226739

**Pull request closed without merging**
